### ISSUE TITLE
NMU Initial Issues

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/Geonode-nmu#1]
**Documents:** 
Some of the document retrieved does not seem to be readable. Only the metadata for them can be seen.
| Document title | Readable | Link |
| :-------- | :------: | :-------- | 
| Principles for transformative ocean governance_Questionnaire1 | No | https://nmu.do.kartoza.com/catalogue/#/document/344 |
| Principles for transformative ocean governance_Questionnaire2 | No | https://nmu.do.kartoza.com/catalogue/#/document/343 |
| Algoa Bay Systematic Conservation Plan 2020 | Yes | https://nmu.do.kartoza.com/catalogue/#/document/286 |
| Marine Living Resources Act No. 18 of 1998: Publication of Policy on the Management of Seals, Seabirds and Shorebirds | Yes |https://nmu.do.kartoza.com/catalogue/#/document/50  |
| Addo Elephant National Park regulations for MPA | Yes | https://nmu.do.kartoza.com/catalogue/#/document/208 |
| Algoa Bay Project EndNote Literature Database | NO | https://nmu.do.kartoza.com/catalogue/#/document/23 |
| Estee Vermeulen PhD proposal | Yes | https://nmu.do.kartoza.com/catalogue/#/document/175 |
| Marine Pollution (Intervention) Act No. 64 of 1987 | Yes | https://nmu.do.kartoza.com/catalogue/#/document/49 |
| Practical approaches and advances in spatial tools to achieve multi-objective marine spatial planning | Yes | https://nmu.do.kartoza.com/catalogue/#/document/181 |
| Algoa Bay Project GeoNode User Instructions | Yes | https://nmu.do.kartoza.com/catalogue/#/document/53 |
| Protection of Personal Information Act_2013-004.pdf | Yes | https://nmu.do.kartoza.com/catalogue/#/document/200 |
| Tidimalo Maphoto Masters Proposal | Yes | https://nmu.do.kartoza.com/catalogue/#/document/179 |
| Tidimalo Maphoto Masters ethics clearance | Yes | https://nmu.do.kartoza.com/catalogue/#/document/180 |
| Marine Spatial Planning Act 2018.pdf | Yes | https://nmu.do.kartoza.com/catalogue/#/document/198 |
| Promotion of Access to Information Act_2000-002.pdf | Yes | https://nmu.do.kartoza.com/catalogue/#/document/199 |
| Key Challenges in Advancing an Ecosystem-Based Approach to Marine Spatial Planning Under Economic Growth Imperatives | Yes | https://nmu.do.kartoza.com/catalogue/#/document/183 |
| Spatial Data Infrastructure Act_2003 54-03.pdf | Yes | https://nmu.do.kartoza.com/catalogue/#/document/201 |
| Algoa Bay Project pamphlet | Yes | https://nmu.do.kartoza.com/catalogue/#/document/6 |
| Maritime Zones Act 1994 Amendment to Schedule 2 | Yes | https://nmu.do.kartoza.com/catalogue/#/document/38 |
| Maritime Zones Act 1994 | Yes | https://nmu.do.kartoza.com/catalogue/#/document/36 |
| Additional information for Fish distributions - Nadine Strydom Lit Review | No | https://nmu.do.kartoza.com/catalogue/#/document/187 |
| Port of Ngqura Establishment Act No. 77 of 1998 | Yes | https://nmu.do.kartoza.com/catalogue/#/document/51 |
| United Nations Convention on the Law of the Sea 1982 | Yes | https://nmu.do.kartoza.com/catalogue/#/document/35 |
| National Framework for Marine Spatial Planning in South Africa 2017 | Yes | https://nmu.do.kartoza.com/catalogue/#/document/57 |
| MPA Declarations in Government Gazette | Yes | https://nmu.do.kartoza.com/catalogue/#/document/188 |
| Estee Vermeulen PhD ethics clearance | Yes | https://nmu.do.kartoza.com/catalogue/#/document/176 |
| Marine Spatial Planning Bill for the Republic of South Africa 2017 | Yes  | https://nmu.do.kartoza.com/catalogue/#/document/56 |
| Algoa Bay CoDyM Brochure | Yes | https://nmu.do.kartoza.com/catalogue/#/document/196 |
| National Environment Management Integrated Coastal Management Act No. 24 of 2008: National Estuarine Management Protocol | Yes | https://nmu.do.kartoza.com/catalogue/#/document/52 |
| The advantages of system dynamics models in decision support for integrated ocean management |Yes  | https://nmu.do.kartoza.com/catalogue/#/document/182 |
| Literature database_2021 | No | https://nmu.do.kartoza.com/catalogue/#/document/202 |

**Datasets with errors:**
| Dataset title | Error | Link | Additional Info |
| -------- | -------- | -------- | -------- |
| MSP_Rec&Tour_AB_WildlifeWatching | Invalid dataset extension: The dataset extension exceed the WGS84 maximum extent [-180, -90, 180, 90] | [link](https://nmu.do.kartoza.com/catalogue/#/dataset/295) | ![image](https://github.com/user-attachments/assets/a6c6db8c-3d40-4204-ab2f-c318ec922612) It seems like the layer's native SRS was set incorrectly as these values are not viable in 4326: ![image](https://github.com/user-attachments/assets/21bc525f-4c59-4b13-ae50-c85c582a00ac) The dataset from GeoServer varies from the original dataset and the original dataset's CRS may be based off of a Cape LO or a UTM zone but the coordinates don't line the data up with the correct area (i.e. Algoa Bay)|

**Comment by EliVolsch** [comment]
@meomancer Client confirmed that we can remove the original faulty layer, and is happy to keep the fixed layer. The layer to be removed is [https://algoabaydata.com/catalogue/#/dataset/295](https://algoabaydata.com/catalogue/#/dataset/295)

**Comment by Jeremy-Prior** [comment]
Old Layer removed:
![image](https://github.com/user-attachments/assets/c7c71a20-5728-4718-bcac-f03b267fd014)

![image](https://github.com/user-attachments/assets/905f5552-2e59-4b16-94db-a9ea7defaf06)
